GameRoom player list & GameLobby basic styling
Code-the-Dream-School/bb-practicum-team-2-front pull request #34
Opened 2023-04-27 03:46 UTC by bhoconnor

## Description

- Maps players into a bullet point list in GameRoom, with some very basic inline styling
- Adds some basic styling into the bullet point list in GameLobby
- Center aligns join room input field in GameLobby

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|   | :sparkles: New feature     |
|  ✓  | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

Sorry no before

### After

**GameRoom changes**: 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/63886520/234754378-720e744b-d4ed-4f55-b04b-29750dcfb0bb.png">

and

**GameLobby changes**: 

<img width="645" alt="image" src="https://user-images.githubusercontent.com/63886520/234754420-43cb73ba-3fdf-4782-8635-3dafe7e5d29e.png">

## Testing Steps / QA Criteria

2023-04-27 03:51 UTC, bhoconnor commented
Note that the above "[Hide profile if not logged in](https://github.com/Code-the-Dream-School/bb-practicum-team-2-front/pull/34/commits/64ba4accdab35c7a6abbba2e9d85faeb5ce27c33)" commit was undone by the later "[Bullet point current GameRoom players & undo hamburger nav changes](https://github.com/Code-the-Dream-School/bb-practicum-team-2-front/pull/34/commits/7b413b5f5833c188b157905a489e0377874c82ff)" commit. 

This branch also has all of the latest `dev` branch incorporated in it (with help from @benochi tonight, hat tip to him).

2023-04-28 03:02 UTC, frankstepanski commented on src/components/GameRoom.js
> +          `http://localhost:4000/api/v1/user/${_id}`,
Can't use hard-coded server URLs anymore. Remember, we are deployed now. Need to use the base_url variable.

2023-04-28 03:03 UTC, frankstepanski requested changes
Need to change the hard-code localhost:4000 URL. We are deployed now. We use the base_url variable now.

2023-04-28 11:59 UTC, mautoranzo requested changes

2023-04-28 11:59 UTC, mautoranzo commented on src/components/GameRoom.js
> +        <button onClick={disconnectRoom}>Disconnect</button>
The button disconnect is not necessary any more, now we have the Logout btn (line 167 this same file)

2023-04-28 17:29 UTC, frankstepanski commented on src/components/GameRoom.js
> +          `http://localhost:4000/api/v1/user/${_id}`,
Can't have hard-coded URL to the server.
```try {
        const response = await fetch(
          `http://localhost:4000/api/v1/user/${_id}`,```

2023-04-28 17:29 UTC, frankstepanski requested changes
Need to update hard-coded server URL

2023-04-29 20:11 UTC, frankstepanski approved these changes
Good updates!

2023-04-29 20:11 UTC, merged